#!/usr/bin/env ruby

require "optparse"

require_relative "lib/selectable"

file_path, load_from, result_variable = nil, nil, nil

options = OptionParser.new do |parser|
    parser.banner = "Usage: ./build-selectable-auto [options]"

    parser.on("--to=PATH") do |path|
        file_path = path
    end

    parser.on("--from=PATH") do |from|
        load_from = from
    end

    parser.on("--save=VARIABLE") do |variable|
        result_variable = variable
    end

    parser.on("--help") do
        puts parser
        exit
    end
end

begin
    ARGV << "--help" if ARGV.empty?
    options.parse!(ARGV)
rescue OptionParser::ParseError
    $stderr.puts($!.to_s)
    exit
end

file_path += "/selectable.sh"

puts "Saving into #{file_path}"
puts "Options will be loaded from #{load_from}"
puts "User's choice will be stored in $#{result_variable.upcase}"

build_selectable(
    file_path,
    {
        :type => "stored",
        :path => load_from,
    },
    {
        :type => "store",
        :variable_name => result_variable.upcase,
    }
)
